### ISSUE TITLE
How to run it

### ISSUE THREAD

**Issue by xiaobaiso** [ju1115kr/emotional-diary#1]
How to run it

**Comment by ju1115kr** [comment]
sorry for my late

this repo is developing now, so if you run this repo, can't start rightly.

$ npm install --save
$ ionic serve
(if you installed android studio and AVD(Android 8.0 is required), you can run it. (ex) $ cordova run android )

but you can run server API (server/ directory by flask)

$ cd server
$ pip install -r requirements.txt
$ python manage.py rs

then, you can run server APIs

thanks
